[package]
name = "scicalc_webapp"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
env_logger = "0.11.3"
eval = "0.4.3"
log = "0.4.22"
nom = "8.0.0-alpha2"
serde = "1.0.203"
serde_derive = "1.0.203"
serde_json = "1.0.120"
